apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: mariadb
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mariadb
  storageClassName: local-path
