apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend-container
        image: nginx:1.23
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: curlimages/curl:7.88.1
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Sending request to backend..."
            curl -s http://backend-service.backend
            sleep 5
          done
        ports:
        - containerPort: 80
