apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-static
data:
  nginx.conf: | 
    events { }
    http {
        server {
            listen 443 ssl;
            ssl_certificate /etc/nginx/tls/tls.crt
            ssl_certificate_key /etc/nginx/tls/tls.key;
            ssl_protocols TLSv1.3 TLSv1.2;
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }