apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: relative-fawn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1250Mi
          requests:
            cpu: 800m
            memory: 900Mi
      initContainers:
      - name: init-db
        image: busybox:stable
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c", "echo Initializing DB; sleep 5" ]
        resources:
          limits:
            cpu: 1
            memory: 750Mi
          requests:
            cpu: 800m
            memory: 600Mi
        